name:                work
version:             0.1.0.0
github:              "motoyak/work"
license:             BSD3
author:              "Motohiro Yakura"
maintainer:          "motohiro686@gmail.com"
copyright:           "2019 Motohiro Yakura"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/motoyak/work#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- checkers
- hspec
- containers
- time
- text
- uuid
- wreq
- bytestring
- transformers

library:
  source-dirs: src

executables:
  work-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - work

tests:
  work-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - work
